### ISSUE TITLE
Min SDK 19

### ISSUE THREAD

**Issue by zihadrizkyef** [swapnil1104/CurveGraphView#3]
Hi Swapnil, your library is awesome

But i have a question, why i cannot use it in SDK 19?

**Comment by swapnil1104** [comment]
Hi @zihadrizkyef, glad you like the library.
I don't see any issue with this being backward compatible till SDK 19, it should be fairly simple to add support for it as well.
Would you pick it up, I'll look at your PR and merge it. 
Let me know if you're unable to/ or facing some issues, I'll create another release with SDK 19.

**Comment by zohaib012345** [comment]
i Swapnil, your library is amazing

But i am also having same issue as zihad,  i cannot use it in SDK 19?

**Comment by zihadrizkyef** [comment]
> Would you pick it up, I'll look at your PR and merge it.

Done

**Comment by swapnil1104** [comment]
Hi @zohaib012345, @zihadrizkyef has already raised a PR for this, will get this merged ASAP and push out a release, with which you can use it from SDK 17.

**Comment by zohaib012345** [comment]
> Hi @zohaib012345, @zihadrizkyef has already raised a PR for this, will get this merged ASAP and push out a release, with which you can use it from SDK 17.

thank you bro..

**Comment by swapnil1104** [comment]
Hi, Please pick up the latest release, with the PR merged, version : 2.0.4 
https://github.com/swapnil1104/CurveGraphView/releases/tag/2.0.4

**Comment by zohaib012345** [comment]
> Hi, Please pick up the latest release, with the PR merged, version : 2.0.4
> https://github.com/swapnil1104/CurveGraphView/releases/tag/2.0.4

will it work for linear graph ?

**Comment by swapnil1104** [comment]
It should work for both curved and linear graph.

**Comment by zohaib012345** [comment]
> It should work for both curved and linear graph.

thanks man

**Comment by zohaib012345** [comment]
> It should work for both curved and linear graph.

ERROR: Failed to resolve: com.github.swapnil1104:LinearGraphView:2.0.4

**Comment by zohaib012345** [comment]
can you share dependency here

**Comment by swapnil1104** [comment]
That should work now, please retry.
