### ISSUE TITLE
Graph labels

### ISSUE THREAD

**Issue by riddhee** [swapnil1104/CurveGraphView#5]
I want vertical labels to the left side and also i want x and y both axis
can you please help me to achieve this?

**Comment by riddhee** [comment]
Hi can u please help me t o achieve this?

**Comment by swapnil1104** [comment]
Hi, can you describe what behaviour you are expecting?
You have the option of setting Y axis values as well, just have to enable from Builder.

**Comment by riddhee** [comment]
Hi
i want Y axis value on left side which is crrently on right side of graph
and currently it has only vertical guide line i want horizontal guideline too.

**Comment by swapnil1104** [comment]
Hi, I can work on the vertical guidelines soon, but adding the labels on the left side will require considerable dev effort and refactoring, which I will not be able to pick up soon.

**Comment by swapnil1104** [comment]
https://github.com/swapnil1104/CurveGraphView/pull/7 
@riddhee  working on horizontal guidelines, please check the documentation in the PR to see if this caters to your use case.

**Comment by riddhee** [comment]
Hi
Thank you very much for your support
i really appreciate it
i will check and let you know

**Comment by riddhee** [comment]
will you please share your email so i can share a reference image with u?

**Comment by swapnil1104** [comment]
Please add the image here itself, or mail me at swapniltiwari775@gmail.com

**Comment by riddhee** [comment]
![Screenshot_2020-04-18 Zeplin - Project](https://user-images.githubusercontent.com/38040977/79859490-b62bcb80-83ee-11ea-8f0e-365be120ef50.png)

**Comment by riddhee** [comment]
i want this type of graph

**Comment by swapnil1104** [comment]
Hi, having a level of customizability this high won't be possible in the current scope, if you can break it down and add smaller feature requests I can pick them up instead.
