### ISSUE TITLE
not found .setHorizontalGuideline in version 2.0.4

### ISSUE THREAD

**Issue by webserveis** [swapnil1104/CurveGraphView#8]
**Describe the bug**
version library: 2.0.4
`.setHorizontalGuideline(2) //unresolve  referece: setHorizontalGuideline`

        curveGraphView.configure(
            CurveGraphConfig.Builder(this)
                .setAxisColor(R.color.md_blue_400) // Set number of values to be displayed in X ax
                .setGuidelineColor(R.color.md_grey_500)
                .setGuidelineCount(3)
                .setHorizontalGuideline(2) //unresolve  referece: setHorizontalGuideline

**Comment by swapnil1104** [comment]
Please clean and rebuild and try again.

**Comment by swapnil1104** [comment]
Closing the issue assuming the problem has been solved, let me know if it is still persisting.
